name: Automated API tests using Newman

on:
  push:
    branches: [ "main" ]
      
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman
        
      - name: Install Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: newman run Books.postman_collection.json -e Api_books.postman_environment.json -r htmlextra,cli --reporter-htmlextra-export newman-report.html

      - name: Upload HTMLEXtra Report
        if: always()  # Ensures report is uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: postman-htmlextra-report
          path: newman-report.html



      
