name: Automated API tests using Newman

on:
  push:
    branches: [ "main" ]
      
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run Books.postman_collection.json -e Api_books.postman_environment.json 



      
